  // To get all icons data
  var icons = 

  [{"name":"Developer","link":"./images/icons/Developer.png"},
  {"name":"Calculator","link":"./images/icons/Calculator.png"},
  {"name":"FaceTime","link":"./images/icons/FaceTime.png"}, 
  {"name":"EasyFind","link":"./images/icons/EasyFind.png"}, 
  {"name":"Calender","link":"./images/icons/Calendar.png"}, 
  {"name":"Cobook","link":"./images/icons/Cobook.png"}, 
  {"name":"CandyBar","link":"./images/icons/CandyBar.png"},
  {"name":"Compass","link":"./images/icons/Compass.png"},
  {"name":"Users","link":"./images/icons/Users.png"},
  {"name":"Developer","link":"./images/icons/Developer.png"},
  {"name":"Downloads","link":"./images/icons/Downloads.png"},
  {"name":"Finder","link":"./images/icons/Finder.png"}, 
  {"name":"Doo","link":"./images/icons/Doo.png"}, 
  {"name":"Dictionary","link":"./images/icons/Dictionary.png"}, 
  {"name":"Contacts","link":"./images/icons/Contacts.png"}, 
  {"name":"InDesign","link":"./images/icons/InDesign.png"},
  {"name":"Camera","link":"./images/icons/Camera.png"},
  
  {"name":"CloudApp","link":"./images/icons/CloudApp.png"},
  {"name":"Notes","link":"./images/icons/Notes.png"},
  {"name":"Music","link":"./images/icons/Music.png"},
  {"name":"Passbook","link":"./images/icons/Passbook.png"}, 
  {"name":"Photoshop","link":"./images/icons/Photoshop.png"},
  {"name":"Finder","link":"./images/icons/Finder.png"}, 
  {"name":"Doo","link":"./images/icons/Doo.png"}, 
  {"name":"Dictionary","link":"./images/icons/Dictionary.png"}, 
  {"name":"Contacts","link":"./images/icons/Contacts.png"}, 
  {"name":"InDesign","link":"./images/icons/InDesign.png"},
  {"name":"Camera","link":"./images/icons/Camera.png"},
  {"name":"Users","link":"./images/icons/Users.png"},
  {"name":"Developer","link":"./images/icons/Developer.png"},
  {"name":"Downloads","link":"./images/icons/Downloads.png"},
  {"name":"Finder","link":"./images/icons/Finder.png"}, 
  {"name":"Doo","link":"./images/icons/Doo.png"}, 
  {"name":"Dictionary","link":"./images/icons/Dictionary.png"}, 
  {"name":"Contacts","link":"./images/icons/Contacts.png"}, 
  {"name":"InDesign","link":"./images/icons/InDesign.png"},
  {"name":"Camera","link":"./images/icons/Camera.png"},
  {"name":"Calculator","link":"./images/icons/Calculator.png"},
  {"name":"FaceTime","link":"./images/icons/FaceTime.png"}, 
  {"name":"EasyFind","link":"./images/icons/EasyFind.png"}];

  var menus = 

  [{"name":"FaceTime","link":"./images/icons/Phone.png"},
  {"name":"Calculator","link":"./images/icons/Mail.png"},
  {"name":"Safari","link":"./images/icons/Safari.png"}, 
  {"name":"EasyFind","link":"./images/icons/Settings.png"}]